In [ ]:
import numpy as np
import pandas as pd

In [ ]:
jobs = pd.read_csv('naukri_data_science_jobs_india.csv')
jobs.head()

,Job_Role,Company,Location,Job Experience,Skills/Description
0,Senior Data Scientist,UPL,"Bangalore/Bengaluru, Mumbai (All Areas)",3-6,"python, MLT, statistical modeling, machine lea..."
1,Senior Data Scientist,Walmart,Bangalore/Bengaluru,5-9,"Data Science, Machine learning, Python, Azure,..."
2,Applied Data Scientist / ML Senior Engineer (P...,SAP India Pvt.Ltd,Bangalore/Bengaluru,5-10,"Python, IT Skills, Testing, Cloud, Product Man..."
3,Data Scientist,UPL,"Bangalore/Bengaluru, Mumbai (All Areas)",1-4,"python, machine learning, Data Science, data a..."
4,Data Scientist,Walmart,Bangalore/Bengaluru,4-8,"IT Skills, Python, Data Science, Machine Learn..."

In [ ]:
jobs.shape

(12000, 5)

In [ ]:
# since here all columns have importance hence none removed
jobs["Job_Role"].value_counts()
jobs["Company"].value_counts()
jobs["Location"].value_counts()
jobs["Job Experience"].value_counts()
jobs["Skills/Description"].value_counts()

## all are balanced

Skills/Description
Computer science, Manager Quality Assurance, Front end, Coding, Javascript, Test planning, HTML, Application development    8
Data Scientist                                                                                                              8
Python, IT Skills, Basic, Translation, Time management, Fact, Proof reading                                                 7
operations, software, business, Database, Management, technology                                                            7
Manager Quality Assurance, Coding, Consulting, Javascript, Workflow, Test planning, HTML, Application development           6
                                                                                                                           ..
VSTS, Stored Procedures, SSAS, SSIS, DevOps, TSQL, Jira, Git                                                                1
IT Skills, Java, Big Data, Cloud computing, C++, Web services, PAAS, Machine learning                                       1
Aws Lambda, Snowflake, Aws Glue, ELT, AWS Athena, ANSI, DBT, RDBMS                                                          1
Design, SQL, Java, REST, infrastructure modeling, verbal, Docker, written communication                                     1
team lead, MLT, machine learning, aws, Python, IT Skills, Testing, Data Science                                             1
Name: count, Length: 11356, dtype: int64

In [ ]:
jobs = jobs[["Job_Role",'Skills/Description','Company','Location','Job Experience']]
jobs.head()

,Job_Role,Skills/Description,Company,Location,Job Experience
0,Senior Data Scientist,"python, MLT, statistical modeling, machine lea...",UPL,"Bangalore/Bengaluru, Mumbai (All Areas)",3-6
1,Senior Data Scientist,"Data Science, Machine learning, Python, Azure,...",Walmart,Bangalore/Bengaluru,5-9
2,Applied Data Scientist / ML Senior Engineer (P...,"Python, IT Skills, Testing, Cloud, Product Man...",SAP India Pvt.Ltd,Bangalore/Bengaluru,5-10
3,Data Scientist,"python, machine learning, Data Science, data a...",UPL,"Bangalore/Bengaluru, Mumbai (All Areas)",1-4
4,Data Scientist,"IT Skills, Python, Data Science, Machine Learn...",Walmart,Bangalore/Bengaluru,4-8

In [ ]:
jobs.isnull().sum()

## no missing values

Job_Role              0
Skills/Description    0
Company               0
Location              0
Job Experience        0
dtype: int64

In [ ]:
jobs.duplicated().sum()
## no repeatition

np.int64(0)

In [ ]:
jobs.rename(columns={
    'Job_Role': 'job_title',
    'Skills/Description': 'required_skills',
    'Company': 'company',
    'Location': 'location',
    'Job Experience': 'exp_lvl'
}, inplace=True)

jobs.head()

,job_title,required_skills,company,location,exp_lvl
0,Senior Data Scientist,"python, MLT, statistical modeling, machine lea...",UPL,"Bangalore/Bengaluru, Mumbai (All Areas)",3-6
1,Senior Data Scientist,"Data Science, Machine learning, Python, Azure,...",Walmart,Bangalore/Bengaluru,5-9
2,Applied Data Scientist / ML Senior Engineer (P...,"Python, IT Skills, Testing, Cloud, Product Man...",SAP India Pvt.Ltd,Bangalore/Bengaluru,5-10
3,Data Scientist,"python, machine learning, Data Science, data a...",UPL,"Bangalore/Bengaluru, Mumbai (All Areas)",1-4
4,Data Scientist,"IT Skills, Python, Data Science, Machine Learn...",Walmart,Bangalore/Bengaluru,4-8

In [ ]:
jobs.iloc[1].required_skills

'Data Science, Machine learning, Python, Azure, BiqQuery, GCP, PySpark, tensorflow'

In [ ]:
jobs['required_skills'] = jobs['required_skills'].str.lower().str.split(', ')
## list conversion needed because we are usine cosine sil=milarity and TF-IDF CountVectorizer Word embeddings

In [ ]:
jobs['required_skills']

0        [python, mlt, statistical modeling, machine le...
1        [data science, machine learning, python, azure...
2        [python, it skills, testing, cloud, product ma...
3        [python, machine learning, data science, data ...
4        [it skills, python, data science, machine lear...
                               ...
11995    [spark, python, s3, lambda, athena, aws, it sk...
11996    [airflow, bigquery, gcs, kafka, java, shell sc...
11997    [it skills, java, software development, testin...
11998    [powershell, azure data factory, azure, paas, ...
11999    [java, javascript, machine learning, nosql, cl...
Name: required_skills, Length: 12000, dtype: object

In [ ]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_title        12000 non-null  object
 1   required_skills  12000 non-null  object
 2   company          12000 non-null  object
 3   location         12000 non-null  object
 4   exp_lvl          12000 non-null  object
dtypes: object(5)
memory usage: 468.9+ KB

In [ ]:


jobs['company'] = jobs['company'].str.lower()
jobs['location'] = jobs['location'].str.lower()


jobs['job_title'] = jobs['job_title'].str.lower()

# remove words like opening, urgent, etc.
remove_words = ['urgent','opening','role','with','for']

for w in remove_words:
    jobs['job_title'] = jobs['job_title'].str.replace(w, '')

# remove punctuation
jobs['job_title'] = jobs['job_title'].str.replace('[^a-zA-Z ]','',regex=True)

# normalize spaces
jobs['job_title'] = jobs['job_title'].str.strip()

In [ ]:
jobs.head()

,job_title,required_skills,company,location,exp_lvl
0,senior data scientist,"[python, mlt, statistical modeling, machine le...",upl,"bangalore/bengaluru, mumbai (all areas)",3-6
1,senior data scientist,"[data science, machine learning, python, azure...",walmart,bangalore/bengaluru,5-9
2,applied data scientist ml senior engineer pyt...,"[python, it skills, testing, cloud, product ma...",sap india pvt.ltd,bangalore/bengaluru,5-10
3,data scientist,"[python, machine learning, data science, data ...",upl,"bangalore/bengaluru, mumbai (all areas)",1-4
4,data scientist,"[it skills, python, data science, machine lear...",walmart,bangalore/bengaluru,4-8

In [ ]:
jobs['required_skills'].apply(type).value_counts()

required_skills
<class 'list'>    12000
Name: count, dtype: int64

In [ ]:
## space removal because space separated entities will be treated differnetly as separate individuals
jobs['location']=jobs['location'].str.replace(" ","_")
jobs['exp_lvl']=jobs['exp_lvl'].str.replace(" ","_")
jobs['company']=jobs['company'].str.replace(" ","_")
jobs['job_title']=jobs['job_title'].str.replace(" ","_")

jobs['required_skills']=jobs['required_skills'].apply(lambda x:[i.replace(" ","_") for i in x])

In [ ]:
jobs.head()

,job_title,required_skills,company,location,exp_lvl
0,senior_data_scientist,"[python, mlt, statistical_modeling, machine_le...",upl,"bangalore/bengaluru,_mumbai_(all_areas)",3-6
1,senior_data_scientist,"[data_science, machine_learning, python, azure...",walmart,bangalore/bengaluru,5-9
2,applied_data_scientist__ml_senior_engineer_pyt...,"[python, it_skills, testing, cloud, product_ma...",sap_india_pvt.ltd,bangalore/bengaluru,5-10
3,data_scientist,"[python, machine_learning, data_science, data_...",upl,"bangalore/bengaluru,_mumbai_(all_areas)",1-4
4,data_scientist,"[it_skills, python, data_science, machine_lear...",walmart,bangalore/bengaluru,4-8

In [ ]:
jobs['exp_lvl'] = jobs['exp_lvl'].apply(lambda x: [x])
jobs['location'] = jobs['location'].apply(lambda x: [x])

In [ ]:
jobs['tags']=jobs['required_skills']+(jobs['exp_lvl'])

In [ ]:
jobs.head()

,job_title,required_skills,company,location,exp_lvl,tags
0,senior_data_scientist,"[python, mlt, statistical_modeling, machine_le...",upl,"[bangalore/bengaluru,_mumbai_(all_areas)]",[3-6],"[python, mlt, statistical_modeling, machine_le..."
1,senior_data_scientist,"[data_science, machine_learning, python, azure...",walmart,[bangalore/bengaluru],[5-9],"[data_science, machine_learning, python, azure..."
2,applied_data_scientist__ml_senior_engineer_pyt...,"[python, it_skills, testing, cloud, product_ma...",sap_india_pvt.ltd,[bangalore/bengaluru],[5-10],"[python, it_skills, testing, cloud, product_ma..."
3,data_scientist,"[python, machine_learning, data_science, data_...",upl,"[bangalore/bengaluru,_mumbai_(all_areas)]",[1-4],"[python, machine_learning, data_science, data_..."
4,data_scientist,"[it_skills, python, data_science, machine_lear...",walmart,[bangalore/bengaluru],[4-8],"[it_skills, python, data_science, machine_lear..."

In [ ]:
jobs_new=jobs[['company','job_title','tags','location']].copy()

In [ ]:
jobs_new['tags']=jobs_new['tags'].apply(lambda x:" ".join(x))

In [ ]:
jobs_new.head()

,company,job_title,tags,location
0,upl,senior_data_scientist,python mlt statistical_modeling machine_learni...,"[bangalore/bengaluru,_mumbai_(all_areas)]"
1,walmart,senior_data_scientist,data_science machine_learning python azure biq...,[bangalore/bengaluru]
2,sap_india_pvt.ltd,applied_data_scientist__ml_senior_engineer_pyt...,python it_skills testing cloud product_managem...,[bangalore/bengaluru]
3,upl,data_scientist,python machine_learning data_science data_anal...,"[bangalore/bengaluru,_mumbai_(all_areas)]"
4,walmart,data_scientist,it_skills python data_science machine_learning...,[bangalore/bengaluru]

-company ,job title, company, location create vectors of job title and we'll go for closest vectors                    
-used bag of words for text vectorization but switched to tfidf because in BoW frequency directly proportional to importance .                            
 #### Example : python repeated a number of times hence python is important but its not               
 #### tfidf : uniqueness based                   
-combine the words of a tag = large text                      
-find most common words and extract them                   
-now take the tag and find the frequency of previously extracted words in each vector of tags               
-now find the closeness of input to vectors                 
-this is the answer                        
-stop words : words used for sentence formation though not present here but will be ignored in case job description provided as paragraphs

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer#CountVectorizer
cv = TfidfVectorizer(stop_words='english')

In [ ]:
vectors=cv.fit_transform(jobs_new['tags']).toarray()
vectors

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.23819679, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.15698365, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.21838745, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(12000, 6989))

In [ ]:
cv.get_feature_names_out()

array(['10', '11', '11g', ..., 'zookeepers', 'zoominfo', 'zyputer'],
      shape=(6989,), dtype=object)

cosine similarity : we'll calculate angle instead of eucleadian distance (preffered for high dimensional data)  
                                             
refer curse of dimensionality topic

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [ ]:
def recommend_from_skills(data):
    
    # extract skills from JSON
    skills_list = data.get("skills", [])
    
    # convert list → string (same format as before)
    skills = " ".join(skills_list).lower()
    
    resume_vector = cv.transform([skills]).toarray()
    
    similarity_scores = cosine_similarity(resume_vector, vectors)
    
    scores = list(enumerate(similarity_scores[0]))
    
    sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)[:5]
    
    # store results instead of printing
    results = []
    
    for i in sorted_scores:
        row = jobs_new.iloc[i[0]]
        results.append({
            "job_title": row.job_title,
            "company": row.company,
            "location": row.location,
            "score": float(i[1])   # convert numpy float → normal float
        })
    
    return results

In [ ]:
input_json = {
    "skills": ["python", "sql", "machine learning"]
}

output = recommend_from_skills(input_json)
print(output)

[{'job_title': 'data_science_python___to__years', 'company': 'spectral_consultants_-search_and_recruitments_firm', 'location': ['pune,_gurgaon/gurugram,_bangalore/bengaluru'], 'score': 0.6693331014828334}, {'job_title': 'data_scientist__machine_learning_engineer', 'company': 'leading_us_mnc_into_analytics', 'location': ['bangalore/bengaluru,_delhi_/_ncr'], 'score': 0.6002186659176729}, {'job_title': 'senior_data__applied_scientist', 'company': 'microsoft', 'location': ['bangalore/bengaluru'], 'score': 0.5667149168420309}, {'job_title': 'associate_data_scientist', 'company': 'logicplum', 'location': ['trivandrum/thiruvananthapuram'], 'score': 0.5163207025092851}, {'job_title': 'data_engineerdata_science_consultant', 'company': 'career_infosystem', 'location': ['bangalore/bengaluru'], 'score': 0.5153794690756973}]

In [ ]:
jobs_new[jobs_new['tags'].str.contains("python sql machine_learning")].head()

,company,job_title,tags,location
6852,change_leaders_consulting,data_engineer,etl python sql machine_learning nosql airflow ...,[bangalore/bengaluru]
7429,spectral_consultants_-search_and_recruitments_...,data_science_python___to__years,data_science r learning artificial_intelligenc...,"[pune,_gurgaon/gurugram,_bangalore/bengaluru]"